### ISSUE TITLE
Create policy that prohibits the ability to commit to master

### ISSUE THREAD

**Issue by stevespringett** [OWASP/www-policy#19]
The overwhelming majority of policies in this repo have been written without community involvement, without any transparency about how the ideas in the policy came to be, why they're there, or who thought they were good ideas. 

There are several policies in this repo that would be better served simply being deleted and started from scratch.

This ticket is to document what I believe to be a DEFECT in the foundations ability to commit to master without the use of pull requests, community involvement, or even the use of GitHub labels which highlight action items to the community.

Committing to master for policies should NEVER be performed without the use of pull requests and community involvement.

**Comment by stevespringett** [comment]
And I continue to see commits to master on policy changes. Unbelievable.

**Comment by stevespringett** [comment]
True, but as with nearly all these policies, they are inherently flawed. The policy that has gotten the most heat from the community is the community review process itself. It needs serious improvement as it doesn't address basic levels of transparency, nor does it help in promoting collaboration on the policies themselves. Parts of the policy simply need to be rewritten. 

There are lots of threads in the Slack channels that express disappointment that commits to master are being made from multiple individuals. The policy requires an out of band communication to the mailing list, rather than having the conversation in GitHub, on the issue or on the pull request that is at hand. The existing policy essentially attempts to recreate a review process that is already built into GitHub. Why?

In addition, a mailing list becomes spam, and it becomes impossible to get into the details, such as use of specific words to describe something in a policy. The use of the word 'point' in the leaders policy which failed board approval for example. The word 'point' could mean many different things (e.g. 301, CNAME, http meta refresh, hyperlink), most of which would prohibit a chapter or project from hosting their own website. However, if the word 'point' refers to a hyperlink, then a project or chapter can have their own website. Details matter, and a mailing list in not the correct forum for details. GitHub pull requests are.

In addition, but not committing to master and moving the review to GitHub, the policy would solve the lack of transparency that exists today in the community review process.

**Comment by vanderaj** [comment]
We discussed this at the Board meeting today. The first steps will be to:

Rename all OWASP Foundation "master" -> "main"
Train staff in using forks, branches, and PRs to apply changes
Establish branch protection on "main" 

Additionally, I have been using PR's & branches for the new draft policies. These will continue to be the way forward for the draft policies going forward. Whilst in draft, I will take GitHub issues against the draft branch so that we can address them prior to going through the policy review process. 

The process by which the Policy Review Team can take feedback in an open question for the Board. I think we need to ensure that everyone can be heard, which means opportunities to provide private feedback to prevent pile ons, which is something that we saw happen in a very negative way last year, but also to improve the process to allow anonymous publication of feedback, as I know for a fact that multiple individuals declined to provide formal feedback because they felt their (valid) feedback would lead to retaliation by some in the community who are diametrically opposed to their view points. I am open to including GitHub issues as a valid feedback pathway to the policy review process, but that's up to the Board at this point in time to take on my improvements, as well as your feedback on this issue. Please work with Joubin Jabbari to formulate a concrete motion on this topic for a future Board meeting.
