### ISSUE TITLE
Branch Meetup Subscriptions

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-policy#58]
From: John DiLeo @johndileo

Regarding the requirement to pay for Branches' Meetup subscriptions from local event profits...I recommend the policy explicitly address local events being operated under the OWASPx model. Will the license fee paid under that model automatically cover these costs? If not, is OWASP willing and able to invoice the events' organising entities (in our case, AppSec New Zealand Incorporated) for the costs of those subscriptions, so those entities can make payment?

**Comment by vanderaj** [comment]
As branches cannot be operationalized nor supported by our current and next AMS, we are closing all branch issues. We are working on a different approach for regional chapters that want to have branches.

**Comment by johndileo** [comment]
@vanderaj, what does your comment actually mean? What's the AMS? Why is it so hard for the "current and next AMS" to support branches? In what way can't they be "operationalized nor supported"?

Taking a guess that by "AMS" you mean "Annual Meetup Subscription," the 'branch' Meetups in New Zealand are a direct counter-example to the claim that they "cannot be operationalized nor supported." The existing support is working just fine - we just need to work out how the 'extra' Meetup subscriptions are paid for.

Clearly, this is urgent concern for me, since the New Zealand chapter has active branches, currently using separate Meetup groups to manage their activities, which could be orphaned by adoption of a policy that fails to address how we can continue using them.
